spring:
  application:
    name: order-api
  profiles:
    active: standalone

stock:
  strategy:
    default-mode: atomic
  retry:
    optimistic:
      max-attempts: 5
      delay: 50
      multiplier: 2.0
      rethrow-on-recovery: false

order:
  retry:
    max-attempts: 5
    delay: 100
    multiplier: 1.5
